### ISSUE TITLE
v0.2.0 of Rum Goggles, Crashes after signing in to the Chat bot

### ISSUE THREAD

**Issue by tinyplayerss** [tylertravisty/rum-goggles#1]
Every time i Add my username and password and stream url clicked save and it Crashed.

**Comment by tylertravisty** [comment]
Are you including "https://" at the beginning of your stream url? I got it to crash if I copied the url without "https://". I can work on fixing this on my stream tomorrow. Let me know if you're still experiencing the crash with "https://" included.

**Comment by tinyplayerss** [comment]
> Are you including "https://" at the beginning of your stream url? I got it to crash if I copied the url without "https://". I can work on fixing this on my stream tomorrow. Let me know if you're still experiencing the crash with "https://" included.

I added https:// manually like its in my Muscle memory, but it still crashed after Pressing save.
